name: etl
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get install libgeos-dev
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install flake8
          python -m pip install -r etl/requirements.txt
      - name: Run Flake8
        run: |
          flake8 etl --ignore=E501
      - name: Run tests
        run: |
          python -m pytest
